2021-07-07T06:45:44.720361+00:00 app[ultroid.1]: [ INFO/2021-07-07 12:15:44,720] pyUltroid: Ultroid - PLUGIN_CHANNEL - Installed - cricker_score
2021-07-07T06:45:45.321985+00:00 app[ultroid.1]: [ INFO/2021-07-07 12:15:45,321] telethon.client.downloads: Starting direct file download in chunks of 131072 at 0, stride 131072
2021-07-07T06:45:45.526136+00:00 app[ultroid.1]: [ INFO/2021-07-07 12:15:45,525] pyUltroid: Ultroid - PLUGIN_CHANNEL - Installed - cringe
2021-07-07T06:45:46.128123+00:00 app[ultroid.1]: [ INFO/2021-07-07 12:15:46,127] telethon.client.downloads: Starting direct file download in chunks of 131072 at 0, stride 131072
2021-07-07T06:45:46.263230+00:00 app[ultroid.1]: [ INFO/2021-07-07 12:15:46,262] pyUltroid: Ultroid - PLUGIN_CHANNEL - Installed - ttyp
2021-07-07T06:45:46.864996+00:00 app[ultroid.1]: [ INFO/2021-07-07 12:15:46,864] telethon.client.downloads: Starting direct file download in chunks of 131072 at 0, stride 131072
2021-07-07T06:45:46.912155+00:00 app[ultroid.1]: [ INFO/2021-07-07 12:15:46,911] pyUltroid: Ultroid - PLUGIN_CHANNEL - Installed - off_bio
2021-07-07T06:45:47.513951+00:00 app[ultroid.1]: [ INFO/2021-07-07 12:15:47,513] telethon.client.downloads: Starting direct file download in chunks of 131072 at 0, stride 131072
2021-07-07T06:45:47.599329+00:00 app[ultroid.1]: [ INFO/2021-07-07 12:15:47,599] pyUltroid: Ultroid - PLUGIN_CHANNEL - Installed - FLAC
2021-07-07T06:45:48.442331+00:00 app[ultroid.1]: [ INFO/2021-07-07 12:15:48,441] pyUltroid: 
2021-07-07T06:45:48.442342+00:00 app[ultroid.1]:                 ----------------------------------------------------------------------
2021-07-07T06:45:48.442342+00:00 app[ultroid.1]:                     Ultroid has been deployed! Visit @TheUltroid for updates!!
2021-07-07T06:45:48.442343+00:00 app[ultroid.1]:                 ----------------------------------------------------------------------
2021-07-07T06:45:48.442344+00:00 app[ultroid.1]: 
2021-07-07T06:46:48.455419+00:00 app[ultroid.1]: [ INFO/2021-07-07 12:16:48,454] telethon.client.telegrambaseclient: Disconnecting borrowed sender for DC 5
2021-07-07T06:46:48.455651+00:00 app[ultroid.1]: [ INFO/2021-07-07 12:16:48,455] telethon.network.mtprotosender: Disconnecting from 91.108.56.145:443/TcpFull...
2021-07-07T06:46:48.458431+00:00 app[ultroid.1]: [ INFO/2021-07-07 12:16:48,458] telethon.network.mtprotosender: Disconnection from 91.108.56.145:443/TcpFull complete!
2021-07-07T07:23:15.943328+00:00 app[ultroid.1]: [ INFO/2021-07-07 12:53:15,943] telethon.network.mtprotosender: Connecting to 149.154.175.57:443/TcpFull...
2021-07-07T07:23:15.971773+00:00 app[ultroid.1]: [ INFO/2021-07-07 12:53:15,971] telethon.network.mtprotosender: Connection to 149.154.175.57:443/TcpFull complete!
2021-07-07T07:23:16.621822+00:00 app[ultroid.1]: [ INFO/2021-07-07 12:53:16,621] telethon.network.mtprotosender: Disconnecting from 149.154.175.57:443/TcpFull...
2021-07-07T07:23:16.622491+00:00 app[ultroid.1]: [ INFO/2021-07-07 12:53:16,622] telethon.network.mtprotosender: Disconnection from 149.154.175.57:443/TcpFull complete!
2021-07-07T07:23:16.623958+00:00 app[ultroid.1]: [ INFO/2021-07-07 12:53:16,623] telethon.client.uploads: Uploading file of 48325 bytes in 1 chunks of 131072
2021-07-07T08:06:21.437433+00:00 app[ultroid.1]: [ INFO/2021-07-07 13:36:21,437] telethon.client.downloads: Starting direct file download in chunks of 131072 at 0, stride 131072
2021-07-07T08:06:21.484888+00:00 app[ultroid.1]: [ INFO/2021-07-07 13:36:21,484] telethon.client.downloads: File lives in another DC
2021-07-07T08:06:21.486103+00:00 app[ultroid.1]: [ INFO/2021-07-07 13:36:21,485] telethon.network.mtprotosender: Connecting to 149.154.167.50:443/TcpFull...
2021-07-07T08:06:22.250022+00:00 app[ultroid.1]: [ INFO/2021-07-07 13:36:22,249] telethon.network.mtprotosender: Connection to 149.154.167.50:443/TcpFull complete!
2021-07-07T08:06:22.251776+00:00 app[ultroid.1]: [ INFO/2021-07-07 13:36:22,251] telethon.client.telegrambaseclient: Exporting auth for new borrowed sender in DcOption(id=2, ip_address='149.154.167.50', port=443, ipv6=False, media_only=False, tcpo_only=False, cdn=False, static=False, secret=None)
2021-07-07T08:07:49.028180+00:00 app[ultroid.1]: [ INFO/2021-07-07 13:37:49,027] telethon.client.telegrambaseclient: Disconnecting borrowed sender for DC 2
2021-07-07T08:07:49.028538+00:00 app[ultroid.1]: [ INFO/2021-07-07 13:37:49,028] telethon.network.mtprotosender: Disconnecting from 149.154.167.50:443/TcpFull...
2021-07-07T08:07:49.029619+00:00 app[ultroid.1]: [ INFO/2021-07-07 13:37:49,029] telethon.network.mtprotosender: Disconnection from 149.154.167.50:443/TcpFull complete!
2021-07-07T08:40:51.930767+00:00 app[ultroid.1]: [WARNING/2021-07-07 14:10:51,929] telethon.client.users: Telegram is having internal issues PersistentTimestampOutdatedError: Persistent timestamp outdated (caused by GetChannelDifferenceRequest)
2021-07-07T09:53:41.184028+00:00 app[ultroid.1]: [ INFO/2021-07-07 15:23:41,183] telethon.network.connection.connection: The server closed the connection
2021-07-07T09:53:41.195968+00:00 app[ultroid.1]: [ INFO/2021-07-07 15:23:41,195] telethon.network.mtprotosender: Connection closed while receiving data
2021-07-07T09:53:41.196408+00:00 app[ultroid.1]: [ INFO/2021-07-07 15:23:41,196] telethon.network.mtprotosender: Closing current connection to begin reconnect...
2021-07-07T09:53:41.196873+00:00 app[ultroid.1]: [ INFO/2021-07-07 15:23:41,196] telethon.network.mtprotosender: Connecting to 149.154.175.55:443/TcpFull...
2021-07-07T09:53:41.234568+00:00 app[ultroid.1]: [ INFO/2021-07-07 15:23:41,234] telethon.network.mtprotosender: Connection to 149.154.175.55:443/TcpFull complete!
2021-07-07T10:44:57.787793+00:00 app[ultroid.1]: [ERROR/2021-07-07 16:14:57,781] pyUltroid: 1881693709
2021-07-07T10:44:57.787804+00:00 app[ultroid.1]: Traceback (most recent call last):
2021-07-07T10:44:57.787805+00:00 app[ultroid.1]:   File "/usr/local/lib/python3.9/site-packages/pyUltroid/misc/_decorators.py", line 99, in wrapper
2021-07-07T10:44:57.787806+00:00 app[ultroid.1]:     await func(ult)
2021-07-07T10:44:57.787807+00:00 app[ultroid.1]:   File "/root/TeamUltroid/plugins/pmpermit.py", line 407, in approvepm
2021-07-07T10:44:57.787807+00:00 app[ultroid.1]:     _not_approved[uid],
2021-07-07T10:44:57.787808+00:00 app[ultroid.1]: KeyError: 1881693709
2021-07-07T14:25:59.479803+00:00 app[ultroid.1]: [ INFO/2021-07-07 19:55:59,477] telethon.network.mtprotosender: Connecting to 149.154.175.57:443/TcpFull...
2021-07-07T14:25:59.591789+00:00 app[ultroid.1]: [ INFO/2021-07-07 19:55:59,591] telethon.network.mtprotosender: Connection to 149.154.175.57:443/TcpFull complete!
2021-07-07T14:26:00.156625+00:00 app[ultroid.1]: [ INFO/2021-07-07 19:56:00,156] telethon.network.mtprotosender: Disconnecting from 149.154.175.57:443/TcpFull...
2021-07-07T14:26:00.157371+00:00 app[ultroid.1]: [ INFO/2021-07-07 19:56:00,157] telethon.network.mtprotosender: Disconnection from 149.154.175.57:443/TcpFull complete!
2021-07-07T14:26:00.158342+00:00 app[ultroid.1]: [ INFO/2021-07-07 19:56:00,158] telethon.client.uploads: Uploading file of 48325 bytes in 1 chunks of 131072
2021-07-07T14:37:12.959680+00:00 app[ultroid.1]: [ INFO/2021-07-07 20:07:12,959] telethon.client.downloads: Starting direct file download in chunks of 131072 at 0, stride 131072
2021-07-07T14:37:13.044143+00:00 app[ultroid.1]: [ INFO/2021-07-07 20:07:13,043] telethon.client.downloads: File lives in another DC
2021-07-07T14:37:13.055617+00:00 app[ultroid.1]: [ INFO/2021-07-07 20:07:13,051] telethon.network.mtprotosender: Connecting to 149.154.167.50:443/TcpFull...
2021-07-07T14:37:13.147486+00:00 app[ultroid.1]: [ INFO/2021-07-07 20:07:13,147] telethon.network.mtprotosender: Connection to 149.154.167.50:443/TcpFull complete!
2021-07-07T14:37:13.651217+00:00 app[ultroid.1]: [ INFO/2021-07-07 20:07:13,650] telethon.client.uploads: Uploading file of 4604 bytes in 1 chunks of 131072
2021-07-07T14:38:54.399029+00:00 app[ultroid.1]: [ INFO/2021-07-07 20:08:54,398] telethon.client.telegrambaseclient: Disconnecting borrowed sender for DC 2
2021-07-07T14:38:54.399208+00:00 app[ultroid.1]: [ INFO/2021-07-07 20:08:54,399] telethon.network.mtprotosender: Disconnecting from 149.154.167.50:443/TcpFull...
2021-07-07T14:38:54.399923+00:00 app[ultroid.1]: [ INFO/2021-07-07 20:08:54,399] telethon.network.mtprotosender: Disconnection from 149.154.167.50:443/TcpFull complete!
2021-07-07T15:06:23.203749+00:00 app[ultroid.1]: [ERROR/2021-07-07 20:36:23,189] pyUltroid: name 'e' is not defined
2021-07-07T15:06:23.203761+00:00 app[ultroid.1]: Traceback (most recent call last):
2021-07-07T15:06:23.203768+00:00 app[ultroid.1]:   File "/usr/local/lib/python3.9/site-packages/pyUltroid/misc/_decorators.py", line 99, in wrapper
2021-07-07T15:06:23.203769+00:00 app[ultroid.1]:     await func(ult)
2021-07-07T15:06:23.203769+00:00 app[ultroid.1]:   File "/root/TeamUltroid/addons/ibutton.py", line 165, in cbuttom
2021-07-07T15:06:23.203770+00:00 app[ultroid.1]:     eris = await eor(e,"`...`")
2021-07-07T15:06:23.203770+00:00 app[ultroid.1]: NameError: name 'e' is not defined
2021-07-07T15:07:24.287894+00:00 app[ultroid.1]: [ERROR/2021-07-07 20:37:24,272] telethon.client.updates: Unhandled exception on own
2021-07-07T15:07:24.287904+00:00 app[ultroid.1]: Traceback (most recent call last):
2021-07-07T15:07:24.287905+00:00 app[ultroid.1]:   File "/usr/local/lib/python3.9/site-packages/telethon/client/updates.py", line 454, in _dispatch_update
2021-07-07T15:07:24.287906+00:00 app[ultroid.1]:     await callback(event)
2021-07-07T15:07:24.287907+00:00 app[ultroid.1]:   File "/root/TeamUltroid/assistant/start.py", line 56, in own
2021-07-07T15:07:24.287907+00:00 app[ultroid.1]:     await event.edit(
2021-07-07T15:07:24.287908+00:00 app[ultroid.1]:   File "/usr/local/lib/python3.9/site-packages/telethon/events/callbackquery.py", line 320, in edit
2021-07-07T15:07:24.287908+00:00 app[ultroid.1]:     return await self._client.edit_message(
2021-07-07T15:07:24.287909+00:00 app[ultroid.1]:   File "/usr/local/lib/python3.9/site-packages/telethon/client/messages.py", line 1165, in edit_message
2021-07-07T15:07:24.287910+00:00 app[ultroid.1]:     msg = self._get_response_message(request, await self(request), entity)
2021-07-07T15:07:24.287910+00:00 app[ultroid.1]:   File "/usr/local/lib/python3.9/site-packages/telethon/client/users.py", line 30, in __call__
2021-07-07T15:07:24.287911+00:00 app[ultroid.1]:     return await self._call(self._sender, request, ordered=ordered)
2021-07-07T15:07:24.287911+00:00 app[ultroid.1]:   File "/usr/local/lib/python3.9/site-packages/telethon/client/users.py", line 79, in _call
2021-07-07T15:07:24.287911+00:00 app[ultroid.1]:     result = await future
2021-07-07T15:07:24.287912+00:00 app[ultroid.1]: telethon.errors.rpcerrorlist.MessageNotModifiedError: Content of the message was not modified (caused by EditMessageRequest)
2021-07-07T15:07:24.290637+00:00 app[ultroid.1]: [ERROR/2021-07-07 20:37:24,289] telethon.client.updates: Unhandled exception on own
2021-07-07T15:07:24.290638+00:00 app[ultroid.1]: Traceback (most recent call last):
2021-07-07T15:07:24.290638+00:00 app[ultroid.1]:   File "/usr/local/lib/python3.9/site-packages/telethon/client/updates.py", line 454, in _dispatch_update
2021-07-07T15:07:24.290639+00:00 app[ultroid.1]:     await callback(event)
2021-07-07T15:07:24.290639+00:00 app[ultroid.1]:   File "/root/TeamUltroid/assistant/start.py", line 56, in own
2021-07-07T15:07:24.290640+00:00 app[ultroid.1]:     await event.edit(
2021-07-07T15:07:24.290640+00:00 app[ultroid.1]:   File "/usr/local/lib/python3.9/site-packages/telethon/events/callbackquery.py", line 320, in edit
2021-07-07T15:07:24.290640+00:00 app[ultroid.1]:     return await self._client.edit_message(
2021-07-07T15:07:24.290641+00:00 app[ultroid.1]:   File "/usr/local/lib/python3.9/site-packages/telethon/client/messages.py", line 1165, in edit_message
2021-07-07T15:07:24.290641+00:00 app[ultroid.1]:     msg = self._get_response_message(request, await self(request), entity)
2021-07-07T15:07:24.290642+00:00 app[ultroid.1]:   File "/usr/local/lib/python3.9/site-packages/telethon/client/users.py", line 30, in __call__
2021-07-07T15:07:24.290642+00:00 app[ultroid.1]:     return await self._call(self._sender, request, ordered=ordered)
2021-07-07T15:07:24.290643+00:00 app[ultroid.1]:   File "/usr/local/lib/python3.9/site-packages/telethon/client/users.py", line 79, in _call
2021-07-07T15:07:24.290643+00:00 app[ultroid.1]:     result = await future
2021-07-07T15:07:24.290643+00:00 app[ultroid.1]: telethon.errors.rpcerrorlist.MessageNotModifiedError: Content of the message was not modified (caused by EditMessageRequest)
2021-07-07T15:11:16.313736+00:00 app[ultroid.1]: [ INFO/2021-07-07 20:41:16,313] telethon.network.mtprotosender: Connecting to 91.108.56.145:443/TcpFull...
2021-07-07T15:11:18.332393+00:00 app[ultroid.1]: [ INFO/2021-07-07 20:41:18,332] telethon.network.mtprotosender: Connection to 91.108.56.145:443/TcpFull complete!
2021-07-07T15:11:18.342732+00:00 app[ultroid.1]: [ INFO/2021-07-07 20:41:18,337] telethon.client.telegrambaseclient: Exporting auth for new borrowed sender in DcOption(id=5, ip_address='91.108.56.145', port=443, ipv6=False, media_only=False, tcpo_only=False, cdn=False, static=False, secret=None)
2021-07-07T15:12:21.454943+00:00 app[ultroid.1]: [ INFO/2021-07-07 20:42:21,454] telethon.client.telegrambaseclient: Disconnecting borrowed sender for DC 5
2021-07-07T15:12:21.455269+00:00 app[ultroid.1]: [ INFO/2021-07-07 20:42:21,455] telethon.network.mtprotosender: Disconnecting from 91.108.56.145:443/TcpFull...
2021-07-07T15:12:21.456337+00:00 app[ultroid.1]: [ INFO/2021-07-07 20:42:21,456] telethon.network.mtprotosender: Disconnection from 91.108.56.145:443/TcpFull complete!
2021-07-07T16:16:20.719728+00:00 app[ultroid.1]: sh: 1: spotdl: not found
